version: '3.9'

services:
  api:
    container_name: rest-service-api
    image: rest-service-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - rest-service-network
    restart: on-failure
    depends_on:
      - db
    command: ['npm', 'run', 'start:dev']

  db:
    container_name: rest-service-db
    image: rest-service-db
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - .env
    networks:
      - rest-service-network
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      PG_DATA: /var/lib/postgresql/data
networks:
  rest-service-network:
    driver: bridge
